### ISSUE TITLE
Plugin settings reset after closing the game

### ISSUE THREAD

**Issue by OneCrazyRussian** [Haplo064/ChatBubbles#54]
Currently I have to setup settings from scratch every time I open the game, they do persist if I don't close the game (i.e. log out) but don't if I close and reopen the game itself

Other plugins don't seem to exhibit same problem

I'm using 150% UI scaling and fullscreen mode (DLDSR 2.25x), maybe the scaling options break something

**Comment by MKhayle** [comment]
Sounds like an almost duplicate issue of #53 ; 

I can't replicate this issue ; you may have an older config version which hasn't been updated. I'd advise you to follow this process to reset your config file :

- Exit the game if it's running
- Delete/change the file name of your config file in `%appdata%/XIVLauncher/pluginConfigs/ChatBubbles.json`
- Restart the game, and attempt to open config
- if it doesn't show the save option, please type `/xllog`, re-attempt to open the config and report any ChatBubbles-related error which could spawn. 

If that worked out for you, please close this issue, thanks !

**Comment by OneCrazyRussian** [comment]
I get following errors in log:
```
--------------------------------
21:59:21.934 | INF [ChatBubbles] Error before updating frame: System.NullReferenceException: Object reference not set to an instance of an object.
   at FFXIVClientStructs.FFXIV.Component.GUI.AtkResNode.get_IsVisible() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\FFXIV\Component\GUI\AtkResNode.cs:line 104
   at ChatBubbles.ChatBubbles.OnceUponAFrame(Object _) in /work/repo/ChatBubbles/OnceUponAFrame.cs:line 189
--------------------------------
21:59:21.945 | INF [Dalamud] Error before updating frame: System.NullReferenceException: Object reference not set to an instance of an object.
   at FFXIVClientStructs.FFXIV.Component.GUI.AtkResNode.get_IsVisible() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\FFXIV\Component\GUI\AtkResNode.cs:line 104
   at ChatBubbles.ChatBubbles.OnceUponAFrame(Object _) in /work/repo/ChatBubbles/OnceUponAFrame.cs:line 189
--------------------------------
21:59:21.952 | INF [Dalamud] Error before updating frame: System.NullReferenceException: Object reference not set to an instance of an object.
   at FFXIVClientStructs.FFXIV.Component.GUI.AtkResNode.get_IsVisible() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\FFXIV\Component\GUI\AtkResNode.cs:line 104
   at ChatBubbles.ChatBubbles.OnceUponAFrame(Object _) in /work/repo/ChatBubbles/OnceUponAFrame.cs:line 189
--------------------------------
21:59:21.968 | INF [Dalamud] Error before updating frame: System.NullReferenceException: Object reference not set to an instance of an object.
   at FFXIVClientStructs.FFXIV.Component.GUI.AtkResNode.get_IsVisible() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\FFXIV\Component\GUI\AtkResNode.cs:line 104
   at ChatBubbles.ChatBubbles.OnceUponAFrame(Object _) in /work/repo/ChatBubbles/OnceUponAFrame.cs:line 189
--------------------------------
21:59:21.984 | INF [Dalamud] Error before updating frame: System.NullReferenceException: Object reference not set to an instance of an object.
   at FFXIVClientStructs.FFXIV.Component.GUI.AtkResNode.get_IsVisible() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\FFXIV\Component\GUI\AtkResNode.cs:line 104
   at ChatBubbles.ChatBubbles.OnceUponAFrame(Object _) in /work/repo/ChatBubbles/OnceUponAFrame.cs:line 189
--------------------------------
21:59:22.001 | INF [Dalamud] Error before updating frame: System.NullReferenceException: Object reference not set to an instance of an object.
   at FFXIVClientStructs.FFXIV.Component.GUI.AtkResNode.get_IsVisible() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\FFXIV\Component\GUI\AtkResNode.cs:line 104
   at ChatBubbles.ChatBubbles.OnceUponAFrame(Object _) in /work/repo/ChatBubbles/OnceUponAFrame.cs:line 189
--------------------------------
21:59:22.017 | INF [Dalamud] Error before updating frame: System.NullReferenceException: Object reference not set to an instance of an object.
   at FFXIVClientStructs.FFXIV.Component.GUI.AtkResNode.get_IsVisible() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\FFXIV\Component\GUI\AtkResNode.cs:line 104
   at ChatBubbles.ChatBubbles.OnceUponAFrame(Object _) in /work/repo/ChatBubbles/OnceUponAFrame.cs:line 189
--------------------------------
```
Then after removing the config it got much bigger, notably the missing entries were added
```
  "Timer": 7,
  "BubbleFunctionality": 3,
  "Hide": false,
  "TextScale": false,
  "SelfLock": false,
  "BubbleSize": 1.5,
  "DefaultScale": 1.5,
  "Switch": true,
  "YalmCap": 250,
```

The errors above still persist but the config was correct on game restart, so they must be non related

Can the config entries be created in old config file versions? I.e. I would expect a setting missing in json to be added to it after changing it in ui
